### ISSUE TITLE
No module named 'torch'

### ISSUE THREAD

**Issue by Kurinosuke118** [IDEA-Research/GroundingDINO#106]
Before running setup.py with (1), you need to run (2), right?
(1) pip install -q -e .
(2) pip install torch

**Comment by sophieDataroots** [comment]
I have the same issue

**Comment by tsitsimis** [comment]
Did anyone find a solution to this?

**Comment by remisphere** [comment]
I think this is an unresolved issue.
If PyTorch is a mandatory dependency, then it should be resolved and installed automatically by the package manager.
The problem here is that the `setup.py` file expects [`torch` to be available](https://github.com/IDEA-Research/GroundingDINO/blob/856dde20aee659246248e20734ef9ba5214f5e44/setup.py#L30-L37) even before defining the `setup()` function, in which [dependencies are defined](https://github.com/IDEA-Research/GroundingDINO/blob/856dde20aee659246248e20734ef9ba5214f5e44/setup.py#L211C9-L211C65).

The calling of [`pip` from inside `setup.py`](https://github.com/IDEA-Research/GroundingDINO/blob/856dde20aee659246248e20734ef9ba5214f5e44/setup.py#L34C9-L34C81) feels like a bad hack, and it breaks in environment that don't expose `pip` as a command or use precise versions of PyTorch.

**Comment by Dramwig** [comment]
same

**Comment by inlineHamed** [comment]
I was able to run the inference using this command:
`pip install -r requirements.txt`
and then 
`pip install -e .`

**Comment by Diti0411** [comment]
> I was able to run the inference using this command: `pip install -r requirements.txt` and then `pip install -e .`
I tried running this but I fail
ModuleNotFoundError: No module named 'torch'

**Comment by wraithint** [comment]
most likely a build isolation issue during install setup is happening in an isolated build env. Try using the command below instead

`python -m pip install --no-build-isolation -e .`
